DROP TABLE IF EXISTS secmar_json_engagements_type;

CREATE TABLE secmar_json_engagements_type (
  seamis varchar primary key,
  secmar varchar
);

CREATE INDEX ON secmar_json_engagements_type(secmar);

INSERT INTO secmar_json_engagements_type
  (seamis, secmar)
VALUES
  ('ADMINISTRATION', 'Administration'),
  ('ADMINISTRATION_MER', 'Administration maritime'),
  ('AGENCE_MARITIME', 'Agence maritime'),
  ('ARCC', 'ARCC'),
  ('AUTRE', 'Autre'),
  ('AUTRE_EMBARCATION_LEGERE', 'Autre embarcation légère'),
  ('AUTRE_MOYEN', 'Autre'),
  ('AUTRE_ORGANISME', 'Autre organisme'),
  ('AVION', 'Avion'),
  ('AVIONS', 'Avion'),
  ('BASE_MILITAIRE', 'Base militaire'),
  ('CAISSON', 'Caisson'),
  ('CANOT_TOUT_TEMPS', 'Canot tout-temps'),
  ('CAPITAINERIE_PORT', 'Capitainerie'),
  ('CCMM', 'CCMM'),
  ('CENTRE_NAUTIQUE', 'Centre nautique'),
  ('CENTRE_OPERATIONNEL', 'Centre opérationnel'),
  ('CENTRE_SECOURS', 'Centre secours'),
  ('COMMERCE', 'Commerce'),
  ('CONTROLE_AERIEN', 'Contrôle aérien'),
  ('CORG', 'CORG'),
  ('CTT_NSH1', 'Canot tout-temp'),
  ('DRONE', 'Drone'),
  ('ELS_NSC4', 'Vedette de 4e classe'),
  ('EMBARCATION_LEGERE', 'Autre embarcation légère'),
  ('ETABLISSEMENT_MEDICAL', 'Établissement médical'),
  ('GENDARMERIE_COMMISSARIAT', 'Gendarmerie / Commissariat'),
  ('HELICOPTERE', 'Hélicoptère'),
  ('HOPITAL', 'Hôpital'),
  ('LOCALISATION_GSM', 'Localisation GSM'),
  ('MCC_COSPAS_SARSAT', 'MCC COSPAS SARSAT'),
  ('MEDECIN_HYPERBARE', 'Médecin hyperbare'),
  ('MRCC', 'MRCC'),
  ('NAVIRE_ADMINISTRATION', 'Navire administration'),
  ('NAVIRE_MILITAIRE', 'Navire militaire'),
  ('NAVIRE_PILOTE', 'Navire pilote'),
  ('PATROUILLE', 'Patrouille'),
  ('PECHE', 'Pêche'),
  ('PLAISANCE', 'Plaisance'),
  ('PLONGEUR', 'Plongeur'),
  ('POSTE_PLAGE', 'Poste de plage'),
  ('PUBLIC_INF_40M', 'Navire public de moins de 40m'),
  ('PUBLIC_SUP_40M', 'Navire public de plus de 40m'),
  ('RCC_RSC', 'RCC RSC'),
  ('REMORQUEUR', 'Remorqueur'),
  ('REMORQUEUR_INTERVENTION', 'Remorqueur d''intervention, d''assistance, sauvetage'),
  ('RIAS', 'Remorqueur d''intervention, d''assistance, sauvetage'),
  ('SCMM', 'SCMM'),
  ('SEMAPHORE', 'Sémaphore'),
  ('SMUR', 'SMUR'),
  ('SMUR_M', 'SMUR maritime'),
  ('STATION_RADIO_MARITIME', 'Station radio maritime'),
  ('TMAS', 'TMAS'),
  ('TMAS_CCMM_SCMM', 'TMAS CCMM SCMM'),
  ('V1_NSH2', 'Vedette de 1re classe'),
  ('V2_NSC1', 'Vedette de 2e ou 3e classe'),
  ('V3_NSC2', 'Vedette de 2e ou 3e classe'),
  ('V4_NSC3', 'Vedette de 4e classe'),
  ('VEDETTE_CLASSE_1', 'Vedette de 1re classe'),
  ('VEDETTE_CLASSE_2_3', 'Vedette de 2e ou 3e classe'),
  ('VEDETTE_CLASSE_4', 'Vedette de 4e classe'),
  ('VEHICULE_MEDICALISE', 'Véhicule médicalisé'),
  ('VEHICULE_SANITAIRE', 'Véhicule sanitaire')
;
