DROP TABLE IF EXISTS secmar_json_evenement_codes;

CREATE TABLE secmar_json_evenement_codes (
  seamis varchar,
  secmar varchar,
  categorie_evenement varchar
);

CREATE INDEX ON secmar_json_evenement_codes(secmar);
CREATE UNIQUE INDEX ON secmar_json_evenement_codes (seamis);

INSERT INTO secmar_json_evenement_codes
  (seamis, secmar, categorie_evenement)
VALUES
  ('ABORDAGE', 'Abordage', null),
  ('ABSENCE_COMM', 'Absence d''un moyen de communication', null),
  ('ACCIDENT_AERO', 'Accident aéronautique', null),
  ('ACCIDENT_AERONAUTIQUE', 'Accident aéronautique', null),
  ('ACCIDENT_CORPOREL', 'Autre accident', null),
  ('ACTE_DE_PIRATERIE', 'Acte de piraterie', 'Autres affaires nécessitant opération'),
  ('ATTAQUE_TERRORISTE', 'Attaque terroriste', 'Autres affaires nécessitant opération'),
  ('AUTRE_ACCIDENT', 'Autre accident', null),
  ('AUTRE_EVENEMENT', 'Autre événement', null),
  ('AVARIE_AERONAUTIQUE', 'Accident aéronautique', null),
  ('AVARIE_APPAREIL_A_GOUVERNER', 'Avarie de l''appareil à gouverner', null),
  ('AVARIE_DE_COMMUNICATION', 'Avarie des systèmes de communication', null),
  ('AVARIE_DE_GREEMENT', 'Avarie de l''appareil à gouverner', null),
  ('AVARIE_DE_LAPPAREIL_A_GOUVERNER', 'Avarie de l''appareil à gouverner', null),
  ('AVARIE_DE_PROPULSION', 'Avarie du système de propulsion', null),
  ('AVARIE_ELECTRIQUE', 'Avarie électrique', null),
  ('AVARIE_SYST_COMM', 'Avarie des systèmes de communication', null),
  ('AVARIE_SYST_PROPULSION', 'Avarie du système de propulsion', null),
  ('BAIGNADE', 'Baignade', null),
  ('BLESSE_AVEC_DEROUTEMENT', 'Blessé avec déroutement', null),
  ('BLESSE_EVAMED', 'Blessé EvaMed', null),
  ('BLESSE_EVASAN', 'Blessé EvaSan', null),
  ('BLESSE_PROJ_EQUIPE_MEDICALE', 'Blessé projection d''une équipe médicale', null),
  ('BLESSE_SOIN_SANS_DEROUTEMENT', 'Blessé avec soin sans déroutement', null),
  ('CHASSE_SOUS_MARINE', 'Chasse sous-marine', null),
  ('CHASSE_SOUSMARINE', 'Chasse sous-marine', null),
  ('CHAVIREMENT', 'Chavirement', null),
  ('CHUTE_A_LA_MER', 'Homme à la mer', null),
  ('CHUTE_DUNE_FALAISE', 'Chute falaise / Emporté par une lame', null),
  ('CHUTE_FALAISE', 'Chute falaise / Emporté par une lame', null),
  ('COLLISION', 'Collision', 'Accidents de navire'),
  ('DECOUVERTE_CORPS', 'Découverte de corps', null),
  ('DECOUVERTE_DE_CORPS', 'Découverte de corps', null),
  ('DECOUVERTE_DOBJET', 'Découverte d''explosif', null),
  ('DECOUVERTE_EXPLOSIF', 'Découverte d''explosif', null),
  ('DEMATAGE', 'Démâtage', null),
  ('DESARRIMAGE_DE_CARGAISON', 'Désarrimage cargaison', null),
  ('DIFFICULTE_A_MANOEUVRER', 'Difficulté de manoeuvre', null),
  ('DIFFICULTE_MANOEUVRE', 'Difficulté de manoeuvre', null),
  ('ECHOUEMENT', 'Échouement', null),
  ('EMPORTE_PAR_UNE_LAME', 'Chute falaise / Emporté par une lame', null),
  ('EN_DERIVE', 'Sans avarie en dérive', null),
  ('ENCALMINAGE', 'Encalminage', null),
  ('ENGIN_DANGEREUX_A_BORD', 'Engin dangereux à bord', 'Avaries non suivies d''accident navire'),
  ('ENVASEMENT', 'Envasement', 'Accidents individuels à personnes'),
  ('EXPLOSIF', 'Explosif dans engin', 'Avaries non suivies d''accident navire'),
  ('EXPLOSION', 'Explosion', null),
  ('FAUSSE_ALERTE', 'Toutes fausses alertes', null),
  ('HELICE_ENGAGEE', 'Immobilisé dans engins / hélice engagée', null),
  ('HEURT', 'Heurt', null),
  ('HOMME_A_LA_MER', 'Homme à la mer', null),
  ('IMMIGRATION_CLANDESTINE', 'Immigration clandestine', 'Autres affaires nécessitant opération'),
  ('IMMOBILISE_DANS_ENGIN', 'Immobilisé dans engins / hélice engagée', null),
  ('INCAPACITE_DE_SE_POSITIONNER', 'Incertitude sur la position', null),
  ('INCENDIE', 'Incendie', null),
  ('INCERTITUDE', 'Incertitude', null),
  ('INCERTITUDE_POSITION', 'Incertitude sur la position', null),
  ('INEXPERIENCE', 'Sans avarie inexpérience', null),
  ('ISOLEMENT_MAREE', 'Isolement par la marée / Envasé', null),
  ('ISOLEMENT_PAR_LA_MAREE', 'Isolement par la marée / Envasé', null),
  ('MALADE_AVEC_DEROUTEMENT', 'Malade avec déroutement', null),
  ('MALADE_EVAMED', 'Malade EvaMed', null),
  ('MALADE_EVASAN', 'Malade EvaSan', null),
  ('MALADE_PROJ_EQUIPE_MEDICALE', 'Malade projection d''une équipe médicale', null),
  ('MALADE_SOIN_SANS_DEROUTEMENT', 'Malade avec soin sans déroutement', null),
  ('MOUILLAGE_IMMOBILISE', 'Mouillage immobilisé', 'Avaries non suivies d''accident navire'),
  ('NAUFRAGE', 'Naufrage', 'Accidents de navire'),
  ('PANNE_CARBURANT', 'Panne de carburant', null),
  ('PANNE_DE_CARBURANT', 'Panne de carburant', null),
  ('PERTE_DE_PONTEE', 'Perte de pontée', null),
  ('PERTE_DE_STABILITE', 'Perte de stabilité / Ripage de cargaison', null),
  ('PERTE_STABILITE', 'Perte de stabilité / Ripage de cargaison', null),
  ('PIRATERIE_TERRORISME', 'Acte de piraterie / terrorisme', null),
  ('PLONGEE_APNEE', 'Plongée en apnée', null),
  ('PLONGEE_AUTONOME', 'Plongée autonome', 'Accidents individuels à personnes'),
  ('PLONGEE_BOUTEILLE', 'Plongée avec bouteille', null),
  ('PLONGEE_EN_APNEE', 'Plongée en apnée', null),
  ('PROBLEME_MEDICAL', 'Problème médical', 'Accidents individuels à personnes'),
  ('RIPAGE_DE_CARGAISON', 'Perte de stabilité / Ripage de cargaison', null),
  ('RUPTURE_DE_MOUILLAGE', 'Rupture de mouillage', null),
  ('RUPTURE_MOUILLAGE', 'Rupture de mouillage', null),
  ('SITUATION_INDETERMINEE', 'Incertitude', null),
  ('SUICIDE', 'Suicide', null),
  ('TALONNAGE', 'Talonnage', 'Accidents de navire'),
  ('TENTATIVE_DE_SUICIDE', 'Tentative de suicide', 'Accidents individuels à personnes'),
  ('TRANSPORT_SANITAIRE', 'Transport sanitaire île-continent', null),
  ('TRANSPORT_SANITAIRE_ILECONTINENT', 'Transport sanitaire île-continent', null),
  ('TROUBLE_A_LORDRE_PUBLIC', 'Trouble à l''ordre public', 'Accidents individuels à personnes'),
  ('VOIE_DEAU', 'Voie d''eau', null),
  ('VOIE_EAU', 'Voie d''eau', null)
;
