DROP TABLE IF EXISTS secmar_json_evenement_codes;

CREATE TABLE secmar_json_evenement_codes (
  seamis varchar,
  secmar varchar
);

CREATE UNIQUE INDEX ON secmar_json_evenement_codes (seamis);

-- TODO
-- Certains évènements `secmar` qui ont été créés n'ont pas de valeur de `categorie_evenement`,
-- il faudrait en créer
INSERT INTO secmar_json_evenement_codes
  (seamis, secmar)
VALUES
  ('ABORDAGE', 'Abordage'),
  ('ABSENCE_COMM', 'Absence d''un moyen de communication'),
  ('ACCIDENT_AERO', 'Accident aéronautique'),
  ('ACCIDENT_AERONAUTIQUE', 'Accident aéronautique'),
  ('ACCIDENT_CORPOREL', 'Autre accident'),
  ('ACTE_DE_PIRATERIE', 'Acte de piraterie'),
  ('ATTAQUE_TERRORISTE', 'Attaque terroriste'),
  ('AUTRE_ACCIDENT', 'Autre accident'),
  ('AUTRE_EVENEMENT', 'Autre événement'),
  ('AVARIE_AERONAUTIQUE', 'Accident aéronautique'),
  ('AVARIE_APPAREIL_A_GOUVERNER', 'Avarie de l''appareil à gouverner'),
  ('AVARIE_DE_COMMUNICATION', 'Avarie des systèmes de communication'),
  ('AVARIE_DE_GREEMENT', 'Avarie de l''appareil à gouverner'),
  ('AVARIE_DE_LAPPAREIL_A_GOUVERNER', 'Avarie de l''appareil à gouverner'),
  ('AVARIE_DE_PROPULSION', 'Avarie du système de propulsion'),
  ('AVARIE_ELECTRIQUE', 'Avarie électrique'),
  ('AVARIE_SYST_COMM', 'Avarie des systèmes de communication'),
  ('AVARIE_SYST_PROPULSION', 'Avarie du système de propulsion'),
  ('BAIGNADE', 'Baignade'),
  ('BLESSE_AVEC_DEROUTEMENT', 'Blessé avec déroutement'),
  ('BLESSE_EVAMED', 'Blessé EvaMed'),
  ('BLESSE_EVASAN', 'Blessé EvaSan'),
  ('BLESSE_PROJ_EQUIPE_MEDICALE', 'Blessé projection d''une équipe médicale'),
  ('BLESSE_SOIN_SANS_DEROUTEMENT', 'Blessé avec soin sans déroutement'),
  ('CHASSE_SOUS_MARINE', 'Chasse sous-marine'),
  ('CHASSE_SOUSMARINE', 'Chasse sous-marine'),
  ('CHAVIREMENT', 'Chavirement'),
  ('CHUTE_A_LA_MER', 'Homme à la mer'),
  ('CHUTE_DUNE_FALAISE', 'Chute falaise / Emporté par une lame'),
  ('CHUTE_FALAISE', 'Chute falaise / Emporté par une lame'),
  ('COLLISION', 'Collision'),
  ('DECOUVERTE_CORPS', 'Découverte de corps'),
  ('DECOUVERTE_DE_CORPS', 'Découverte de corps'),
  ('DECOUVERTE_DOBJET', 'Découverte d''explosif'),
  ('DECOUVERTE_EXPLOSIF', 'Découverte d''explosif'),
  ('DEMATAGE', 'Démâtage'),
  ('DESARRIMAGE_DE_CARGAISON', 'Désarrimage cargaison'),
  ('DIFFICULTE_A_MANOEUVRER', 'Difficulté de manoeuvre'),
  ('DIFFICULTE_MANOEUVRE', 'Difficulté de manoeuvre'),
  ('ECHOUEMENT', 'Échouement'),
  ('EMPORTE_PAR_UNE_LAME', 'Chute falaise / Emporté par une lame'),
  ('EN_DERIVE', 'Sans avarie en dérive'),
  ('ENCALMINAGE', 'Encalminage'),
  ('ENGIN_DANGEREUX_A_BORD', 'Engin dangereux à bord'),
  ('ENVASEMENT', 'Envasement'),
  ('EXPLOSIF', 'Explosif dans engin'),
  ('EXPLOSION', 'Explosion'),
  ('FAUSSE_ALERTE', 'Toutes fausses alertes'),
  ('HELICE_ENGAGEE', 'Immobilisé dans engins / hélice engagée'),
  ('HEURT', 'Heurt'),
  ('HOMME_A_LA_MER', 'Homme à la mer'),
  ('IMMIGRATION_CLANDESTINE', 'Immigration clandestine'),
  ('IMMOBILISE_DANS_ENGIN', 'Immobilisé dans engins / hélice engagée'),
  ('INCAPACITE_DE_SE_POSITIONNER', 'Incertitude sur la position'),
  ('INCENDIE', 'Incendie'),
  ('INCERTITUDE', 'Incertitude'),
  ('INCERTITUDE_POSITION', 'Incertitude sur la position'),
  ('INEXPERIENCE', 'Sans avarie inexpérience'),
  ('ISOLEMENT_MAREE', 'Isolement par la marée / Envasé'),
  ('ISOLEMENT_PAR_LA_MAREE', 'Isolement par la marée / Envasé'),
  ('MALADE_AVEC_DEROUTEMENT', 'Malade avec déroutement'),
  ('MALADE_EVAMED', 'Malade EvaMed'),
  ('MALADE_EVASAN', 'Malade EvaSan'),
  ('MALADE_PROJ_EQUIPE_MEDICALE', 'Malade projection d''une équipe médicale'),
  ('MALADE_SOIN_SANS_DEROUTEMENT', 'Malade avec soin sans déroutement'),
  ('MOUILLAGE_IMMOBILISE', 'Mouillage immobilisé'),
  ('NAUFRAGE', 'Naufrage'),
  ('PANNE_CARBURANT', 'Panne de carburant'),
  ('PANNE_DE_CARBURANT', 'Panne de carburant'),
  ('PERTE_DE_PONTEE', 'Perte de pontée'),
  ('PERTE_DE_STABILITE', 'Perte de stabilité / Ripage de cargaison'),
  ('PERTE_STABILITE', 'Perte de stabilité / Ripage de cargaison'),
  ('PIRATERIE_TERRORISME', 'Acte de piraterie / terrorisme'),
  ('PLONGEE_APNEE', 'Plongée en apnée'),
  ('PLONGEE_AUTONOME', 'Plongée autonome'),
  ('PLONGEE_BOUTEILLE', 'Plongée bouteille'),
  ('PLONGEE_EN_APNEE', 'Plongée en apnée'),
  ('PROBLEME_MEDICAL', 'Problème médical'),
  ('RIPAGE_DE_CARGAISON', 'Perte de stabilité / Ripage de cargaison'),
  ('RUPTURE_DE_MOUILLAGE', 'Rupture de mouillage'),
  ('RUPTURE_MOUILLAGE', 'Rupture de mouillage'),
  ('SITUATION_INDETERMINEE', 'Incertitude'),
  ('SUICIDE', 'Suicide'),
  ('TALONNAGE', 'Talonnage'),
  ('TENTATIVE_DE_SUICIDE', 'Tentative de suicide'),
  ('TRANSPORT_SANITAIRE', 'Transport sanitaire île-continent'),
  ('TRANSPORT_SANITAIRE_ILECONTINENT', 'Transport sanitaire île-continent'),
  ('TROUBLE_A_LORDRE_PUBLIC', 'Trouble à l''ordre public'),
  ('VOIE_DEAU', 'Voie d''eau'),
  ('VOIE_EAU', 'Voie d''eau')
;
