DROP TABLE IF EXISTS secmar_json_operations_departement;

CREATE TABLE secmar_json_operations_departement (
  seamis varchar primary key,
  secmar varchar not null,
  est_metropolitain boolean not null
);

INSERT INTO secmar_json_operations_departement
  (seamis, secmar, est_metropolitain)
VALUES
  ('01', 'Ain', true),
  ('02', 'Aisne', true),
  ('03', 'Allier', true),
  ('04', 'Alpes-de-Haute-Provence', true),
  ('05', 'Hautes-Alpes', true),
  ('06', 'Alpes-Maritimes', true),
  ('07', 'Ardèche', true),
  ('08', 'Ardennes', true),
  ('09', 'Ariège', true),
  ('10', 'Aube', true),
  ('11', 'Aude', true),
  ('12', 'Aveyron', true),
  ('13', 'Bouches-du-Rhône', true),
  ('14', 'Calvados', true),
  ('15', 'Cantal', true),
  ('16', 'Charente', true),
  ('17', 'Charente-Maritime', true),
  ('18', 'Cher', true),
  ('19', 'Corrèze', true),
  ('2A', 'Corse-du-Sud', true),
  ('2B', 'Haute-Corse', true),
  ('21', 'Côte-d''Or', true),
  ('22', 'Côtes-d''Armor', true),
  ('23', 'Creuse', true),
  ('24', 'Dordogne', true),
  ('25', 'Doubs', true),
  ('26', 'Drôme', true),
  ('27', 'Eure', true),
  ('28', 'Eure-et-Loir', true),
  ('29', 'Finistère', true),
  ('30', 'Gard', true),
  ('31', 'Haute-Garonne', true),
  ('32', 'Gers', true),
  ('33', 'Gironde', true),
  ('34', 'Hérault', true),
  ('35', 'Ille-et-Vilaine', true),
  ('36', 'Indre', true),
  ('37', 'Indre-et-Loire', true),
  ('38', 'Isère', true),
  ('39', 'Jura', true),
  ('40', 'Landes', true),
  ('41', 'Loir-et-Cher', true),
  ('42', 'Loire', true),
  ('43', 'Haute-Loire', true),
  ('44', 'Loire-Atlantique', true),
  ('45', 'Loiret', true),
  ('46', 'Lot', true),
  ('47', 'Lot-et-Garonne', true),
  ('48', 'Lozère', true),
  ('49', 'Maine-et-Loire', true),
  ('50', 'Manche', true),
  ('51', 'Marne', true),
  ('52', 'Haute-Marne', true),
  ('53', 'Mayenne', true),
  ('54', 'Meurthe-et-Moselle', true),
  ('55', 'Meuse', true),
  ('56', 'Morbihan', true),
  ('57', 'Moselle', true),
  ('58', 'Nièvre', true),
  ('59', 'Nord', true),
  ('60', 'Oise', true),
  ('61', 'Orne', true),
  ('62', 'Pas-de-Calais', true),
  ('63', 'Puy-de-Dôme', true),
  ('64', 'Pyrénées-Atlantiques', true),
  ('65', 'Hautes-Pyrénées', true),
  ('66', 'Pyrénées-Orientales', true),
  ('67', 'Bas-Rhin', true),
  ('68', 'Haut-Rhin', true),
  ('69', 'Rhône', true),
  ('70', 'Haute-Saône', true),
  ('71', 'Saône-et-Loire', true),
  ('72', 'Sarthe', true),
  ('73', 'Savoie', true),
  ('74', 'Haute-Savoie', true),
  ('75', 'Paris', true),
  ('76', 'Seine-Maritime', true),
  ('77', 'Seine-et-Marne', true),
  ('78', 'Yvelines', true),
  ('79', 'Deux-Sèvres', true),
  ('80', 'Somme', true),
  ('81', 'Tarn', true),
  ('82', 'Tarn-et-Garonne', true),
  ('83', 'Var', true),
  ('84', 'Vaucluse', true),
  ('85', 'Vendée', true),
  ('86', 'Vienne', true),
  ('87', 'Haute-Vienne', true),
  ('88', 'Vosges', true),
  ('89', 'Yonne', true),
  ('90', 'Territoire de Belfort', true),
  ('91', 'Essonne', true),
  ('92', 'Hauts-de-Seine', true),
  ('93', 'Seine-Saint-Denis', true),
  ('94', 'Val-de-Marne', true),
  ('95', 'Val-d''Oise', true),
  ('971', 'Guadeloupe', false),
  ('971sb', 'Guadeloupe', false),
  ('971sm', 'Guadeloupe', false),
  ('972', 'Martinique', false),
  ('973', 'Guyane', false),
  ('974', 'La Réunion', false),
  ('975', 'Saint-Pierre-et-Miquelon', false),
  ('976', 'Mayotte', false),
  ('977', 'Saint-Barthélemy', false),
  ('978', 'Saint-Martin', false),
  ('984', 'Terres australes et antarctiques françaises', false),
  ('986', 'Wallis-et-Futuna', false),
  ('987', 'Polynésie', false),
  ('987aus', 'Polynésie', false),
  ('987gam', 'Polynésie', false),
  ('987mar', 'Polynésie', false),
  ('987sdv', 'Polynésie', false),
  ('987ssv', 'Polynésie', false),
  ('987tua', 'Polynésie', false),
  ('988', 'Nouvelle-Calédonie', false),
  ('988sud', 'Nouvelle-Calédonie', false),
  ('989', 'Île de Clipperton', false)
;
