DROP TABLE IF EXISTS secmar_json_operations_qui_alerte;

CREATE TABLE secmar_json_operations_qui_alerte (
  seamis varchar primary key,
  secmar varchar,
  categorie_qui_alerte varchar
);

CREATE INDEX ON secmar_json_operations_qui_alerte(secmar);

INSERT INTO secmar_json_operations_qui_alerte
  (seamis, secmar, categorie_qui_alerte)
VALUES
  ('NAVIRE_IMPLIQUE', 'Navire impliqué', 'Navire à la mer'),
  ('TEMOIN', 'Témoin', 'Organisme ou personne privée'),
  ('CODIS_POMPIERS', 'CODIS / SDIS / CTA', 'Autorité civile française à terre'),
  ('SEMAPHORE', 'Sémaphore', 'Autorité militaire française à terre'),
  ('SAMU', 'SAMU', 'Autorité civile française à terre'),
  ('NAVIRE_PLAISANCE', 'Navire de plaisance', 'Navire à la mer'),
  ('MCC_COSPAS_SARSAT', 'MCC COSPAS-SARSAT', 'Autorité militaire française à terre'),
  ('CORG_GENDARMERIE_NATIONALE', 'CORG / Gendarmerie nationale', 'Autorité militaire française à terre'),
  ('CROSS', 'CROSS / MRCC', 'Autorité maritime française à terre'),
  ('FAMILLE_PROCHE', 'Famille / Proche', 'Organisme ou personne privée'),
  ('SNSM', 'SNSM', 'Organisme ou personne privée'),
  ('PORT', 'Port', 'Organisme ou personne privée'),
  ('PROPRIETAIRE', 'Propriétaire', 'Organisme ou personne privée'),
  ('COMMISSARIAT_POLICE', 'Police', 'Autorité civile française à terre'),
  ('PERSONNE_IMPLIQUEE', 'Navire impliqué', 'Navire à la mer'),
  ('POSTE_PLAGE', 'Poste de plage', 'Organisme ou personne privée'),
  ('NAVIRE_SUPPORT_PLONGEE', 'Support de plongée', 'Organisme ou personne privée'),
  ('CCMM', 'CCMM', 'Autorité maritime française à terre'),
  ('NAVIRE_PECHE', 'Navire de pêche', 'Navire à la mer'),
  ('NAVIRE_A_LA_MER_AUTRE', 'Autre navire à la mer', 'Navire à la mer'),
  ('ADMINISTRATION_ETRANGERE_AUTRE', 'Autre autorité étrangère', 'Autorité étrangère'),
  ('NAVIRE_COMMERCE', 'Navire de commerce', 'Navire à la mer'),
  ('RCC_RSC', 'RCC / RSC', 'Autorité étrangère'),
  ('ORGANISME_AUTRE', 'Autre organisme ou personne privée', 'Organisme ou personne privée'),
  ('NAVIRE_ADMINISTRATION', 'Navire administration civile', 'Navire à la mer'),
  ('NAVIRE_SAUVETAGE', 'Navire de sauvetage', 'Navire à la mer'),
  ('SCMM', 'SCMM', 'Autorité maritime française à terre'),
  ('AERONEF_ADMINISTRATIF', 'Aéronef administratif', 'Aéronef'),
  ('NAVIRE_MILITAIRE', 'Marine nationale', 'Navire à la mer'),
  ('PERSONNE_AUTRE', 'Autre organisme ou personne privée', 'Organisme ou personne privée'),
  ('LOUEUR_BATEAUX', 'Loueur de bateaux', 'Organisme ou personne privée'),
  ('ADMINISTRATION_FRANCAISE_AUTRE', 'Autre administration civile', 'Autorité civile française à terre'),
  ('AGENT_MARITIME', 'Agent maritime', 'Organisme ou personne privée'),
  ('CORGMAR_GENDARMERIE_MARITIME', 'Gendarmerie maritime', 'Autorité militaire française à terre'),
  ('CLUB_PLONGEE', 'Support de plongée', 'Organisme ou personne privée'),
  ('ARMATEUR', 'Armateur', 'Organisme ou personne privée'),
  ('AERONEF_MILITAIRE', 'Aéronef militaire', 'Aéronef'),
  ('COLLECTIVITE_MAIRIE', 'Collectivité locale / Mairie', 'Autorité civile française à terre'),
  ('ECOLE_VOILE', 'École de voile', 'Organisme ou personne privée'),
  ('COD_DOUANE', 'Douane', 'Autorité civile française à terre'),
  ('CONTROLE_AERIEN', 'Contrôle aérien', 'Autorité civile française à terre'),
  ('COMITE_DE_COURSE', 'Comité de course', 'Organisme ou personne privée'),
  ('COM_MARINE_NATIONALE', 'Marine nationale', 'Autorité militaire française à terre'),
  ('ARCC_ARSC', 'ARCC ARSC', 'Autorité civile française à terre'),
  ('AFFAIRES_MARITIMES_CSN', 'Affaires maritimes / CSN', 'Autorité maritime française à terre'),
  ('AERONEF_CIVIL', 'Aéronef civil', 'Aéronef'),
  ('AERONEF_IMPLIQUE', 'Aéronef impliqué', 'Aéronef'),
  ('PILOTAGE_MARITIME', 'Pilotage', 'Organisme ou personne privée'),
  ('AERONEF_AUTRE', 'Autre aéronef', 'Aéronef'),
  ('SERVICE_GEOLOC_PRIVE', 'Service de géolocalisation privé', 'Organisme ou personne privée'),
  ('PREFECTURE_MARITIME', 'Préfecture terrestre ou maritime', 'Autorité militaire française à terre'),
  ('COZ_SECURITE_CIVILE', 'COZ / Sécurité civile', 'Autorité civile française à terre'),
  ('PREFECTURE_TERRESTRE', 'Préfecture', 'Autorité civile française à terre'),
  ('PHARES_BALISES', 'Phares et balises', 'Autorité civile française à terre'),
  ('STATION_RADIO_MARITIME', 'Station radio-maritime', 'Organisme ou personne privée'),
  ('ORGANISME_PROFESSIONNEL_PECHEURS', 'Organisme professionnel / Pêcheur', 'Organisme ou personne privée'),
  ('COMPAGNIE_ASSURANCE', 'Compagnie d''assurance', 'Organisme ou personne privée'),
  ('SHOM', 'SHOM', 'Autorité militaire française à terre'),
  ('AMBASSADE_CONSULAT', 'Ambassade / consulat', 'Autorité civile française à terre'),
  ('COGIC_INTERMINISTERIEL', 'COGIC interministériel', 'Autorité civile française à terre'),
  ('RADIO_AMATEUR', 'Radio amateur', 'Organisme ou personne privée')
;
